easy_admin:
    design:
        menu:
            - { label: 'Home', route: 'default', icon: 'home' }
            - { entity: 'AgentStat', icon: 'home' }
            - Comment
            - TestStat
            - Event
    site_name: '4E DB'
    entities:
        AgentStat:
            class: App\Entity\AgentStat
            label: 'dbadmin.label.stats'
            list:
                fields: ['id', 'datetime', 'agent']
                filters: ['agent', 'datetime']
        Comment:
            class: App\Entity\Comment
        TestStat:
            class: App\Entity\TestStat
        Event :
            class: App\Entity\Event
        # List the entity class name you want to manage
#        - App\Entity\AgentStat
#        -
#        - App\Entity\User
#        -
#        -
