twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    paths:
        "%kernel.project_dir%/public": public_path
        '%kernel.project_dir%/assets/images': images
        '%kernel.project_dir%/assets/css': styles
    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true
