language: php
php:
  - '7.4'
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - composer install
  - npm install
  - npm run dev

script:
  - ./bin/phpunit $PHPUNIT_FLAGS
#  - cat ./var/log/test.log

after_script:
  - bash ./bin/telegram_notification.sh
  - bash ./bin/console
