version: '3'
services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports: [5432]
###< doctrine/doctrine-bundle ###

#volumes:
###> doctrine/doctrine-bundle ###
#  database_data:
###< doctrine/doctrine-bundle ###
