<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260321172807 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agent ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE agent ALTER faction_id DROP NOT NULL');
        $this->addSql('ALTER TABLE agent_stat ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE agent_stat ALTER agent_id DROP NOT NULL');
        $this->addSql('ALTER TABLE agent_stat ALTER datetime DROP NOT NULL');
        $this->addSql('ALTER TABLE agent_user ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE challenge ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE challenge ALTER date_start DROP NOT NULL');
        $this->addSql('ALTER TABLE challenge ALTER date_end DROP NOT NULL');
        $this->addSql('ALTER TABLE comment ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE comment ALTER agent_id DROP NOT NULL');
        $this->addSql('ALTER TABLE comment ALTER datetime DROP NOT NULL');
        $this->addSql('ALTER TABLE comment ALTER commenter_id DROP NOT NULL');
        $this->addSql('ALTER TABLE event ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE event ALTER date_start DROP NOT NULL');
        $this->addSql('ALTER TABLE event ALTER date_end DROP NOT NULL');
        $this->addSql('ALTER TABLE faction ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE fs_data ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE help ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE ingress_event ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE ingress_event ALTER date_start DROP NOT NULL');
        $this->addSql('ALTER TABLE ingress_event ALTER date_end DROP NOT NULL');
        $this->addSql('ALTER TABLE map_group ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE test_stat ALTER id DROP IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agent ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE agent ALTER faction_id SET NOT NULL');
        $this->addSql('ALTER TABLE agent_stat ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE agent_stat ALTER datetime SET NOT NULL');
        $this->addSql('ALTER TABLE agent_stat ALTER agent_id SET NOT NULL');
        $this->addSql('ALTER TABLE agent_user ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE challenge ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE challenge ALTER date_start SET NOT NULL');
        $this->addSql('ALTER TABLE challenge ALTER date_end SET NOT NULL');
        $this->addSql('ALTER TABLE comment ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE comment ALTER datetime SET NOT NULL');
        $this->addSql('ALTER TABLE comment ALTER agent_id SET NOT NULL');
        $this->addSql('ALTER TABLE comment ALTER commenter_id SET NOT NULL');
        $this->addSql('ALTER TABLE event ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE event ALTER date_start SET NOT NULL');
        $this->addSql('ALTER TABLE event ALTER date_end SET NOT NULL');
        $this->addSql('ALTER TABLE faction ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE fs_data ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE help ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE ingress_event ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE ingress_event ALTER date_start SET NOT NULL');
        $this->addSql('ALTER TABLE ingress_event ALTER date_end SET NOT NULL');
        $this->addSql('ALTER TABLE map_group ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE test_stat ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }
}
