<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240423122725 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agent ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE agent_stat ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE agent_user ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE challenge ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE comment ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE event ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE faction ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE fs_data ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE fs_data ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN fs_data.created_at IS \'\'');
        $this->addSql('ALTER TABLE help ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE ingress_event ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE map_group ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE test_stat ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE test_stat ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE agent_stat ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE agent_user ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE fs_data ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE fs_data ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN fs_data.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE challenge ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE agent ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE help ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE comment ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE event ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE map_group ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE ingress_event ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE faction ALTER id DROP IDENTITY');
    }
}
